{% set name = "datalad" %}
{% set version = "0.17.6" %}
{% set sha256 = "b9e2667dac2af7b816c875ea7920431efa7a16248e20276f502e3cb5aa0cc554" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-BF-disable-testing-for-exit-code-for-batched-process.patch

build:
  number: 1
  entry_points:
    - datalad=datalad.cmdline.main:main
    - git-annex-remote-datalad-archives=datalad.customremotes.archives:main
    - git-annex-remote-datalad=datalad.customremotes.datalad:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  # Do not even attempt until we get git-annex in there
  # py 3.6 is the minimal supported version as of 0.14.0
  skip: true  # [py<37]

requirements:
  host:
    - python
    - pip
    - setuptools
    - packaging
    - pypandoc

  run:
    - annexremote
    - boto
    - chardet >=3.0.4
    - colorama  # [win]
    - distro  # [py>=38]
    - exifread
    - fasteners
    - git  # [not win]
    - git-annex  # [linux]
    - humanize
    - importlib-metadata >=3.6  # [py<310]
    - iso8601
    - keyring >=8.0
    - keyrings.alt
    - mutagen >=1.36  # [not (win and py>=39)]
    - msgpack-python
    - 7zip  # [win]
    - p7zip  # [not win]
    - patool >=1.7
    - platformdirs
    - pyperclip  # [not (win and py>=39)]
    - python-gitlab
    - pillow  # [not (win and py>=39)]
    - python
    - python-dateutil
    # TODO
    # - python-xmp-toolkit
    - psutil
    - requests >=1.2
    - requests-ftp
    - secretstorage  # [linux]
    - setuptools
    - simplejson
    - tqdm
    - whoosh

test:
  imports:
    - datalad

  requires:
    - BeautifulSoup4
    - httpretty >=0.8.14
    - mock
    - nibabel
    - pytest
    - pytest-fail-slow
    - packaging
    - vcrpy

  source_files:
    - tox.ini

about:
  home: http://datalad.org
  license: MIT
  license_file: COPYING
  summary: data distribution geared toward scientific datasets
  description: |
    DataLad aims to make data management and data distribution more accessible.
    To do that it stands on the shoulders of Git and Git-annex to deliver a
    decentralized system for data exchange. This includes automated ingestion of
    data from online portals, and exposing it in readily usable form as Git(-annex)
    repositories, so-called datasets. The actual data storage and permission
    management, however, remains with the original data providers.
  doc_url: http://datalad.readthedocs.io/
  dev_url: https://github.com/datalad/datalad

extra:
  recipe-maintainers:
    - yarikoptic
    - notestaff
    - mih
    - jwodder
