{% set name = "datalad" %}
{% set version = "0.13.0" %}
{% set sha256 = "6dcacdcfe0817568da5561b9f14e5bc515170ab367aba188658a16bce1ffd4ea" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
  - 0001-BF-skip-running-testremote-with-recent-not-yet-fixed.patch
  - 0001-BF-annotate-tests-in-test_utils_cached_dataset-with-.patch
  - 0002-BF-TST-skip-one-case-of-test_ria_basics.test_binary_.patch
  - 0001-ENH-TST-use-assert_equal-to-see-why-conda-python-3.8.patch

build:
  number: 0
  entry_points:
    - datalad=datalad.cmdline.main:main
    - git-annex-remote-datalad-archives=datalad.customremotes.archives:main
    - git-annex-remote-datalad=datalad.customremotes.datalad:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  # Do not even attempt until we get git-annex in there
  # py 3.5 is the minimal supported version as of 0.12.0
  skip: true  # [py<35]

requirements:
  build:
    - python
    - pip
    - setuptools
    - pypandoc

  run:
    - appdirs
    - annexremote
    - boto
    - chardet >=3.0.4
    - colorama  # [win]
    - distro  # [py>=38]
    - exifread
    - fasteners
    - git-annex  # [linux]
    - gitpython >=2.1.12
    - humanize
    - iso8601
    - jsmin
    - keyring >=8.0
    - keyrings.alt
    - mock >=1.0.1
    - mutagen >=1.36
    - msgpack-python
    - p7zip  # [not win]
    - patool >=1.7
    - pygithub
    - pyld <0.8|>=0.8.2
    - pyperclip
    - pyyaml
    - pillow
    - python
    - python-dateutil
    # TODO
    # - python-xmp-toolkit
    - psutil
    - requests >=1.2
    - requests-ftp
    - secretstorage  # [linux and py>32]
    - simplejson
    - six >=1.8.0
    - tqdm
    - whoosh
    - wrapt

test:
  imports:
    - datalad

  requires:
    - BeautifulSoup4
    - httpretty >=0.8.14
    - mock
    - nibabel
    - nose >=1.3.4
    - vcrpy

about:
  home: http://datalad.org
  license: MIT
  license_file: COPYING
  summary: data distribution geared toward scientific datasets
  description: |
    DataLad aims to make data management and data distribution more accessible.
    To do that it stands on the shoulders of Git and Git-annex to deliver a
    decentralized system for data exchange. This includes automated ingestion of
    data from online portals, and exposing it in readily usable form as Git(-annex)
    repositories, so-called datasets. The actual data storage and permission
    management, however, remains with the original data providers.
  doc_url: http://datalad.readthedocs.io/
  dev_url: https://github.com/datalad/datalad

extra:
  recipe-maintainers:
    - yarikoptic
    - notestaff
    - kyleam
    - mih
